name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-tests:
    name: Backend (Jest)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Run Jest
        working-directory: backend
        run: npm test

  frontend-e2e:
    name: Frontend (Playwright E2E)
    runs-on: ubuntu-latest
    needs: backend-tests

    services:
      mongo:
        image: mongo:6
        ports: ['27017:27017']
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGODB_URI: mongodb://127.0.0.1:27017/book_store_ci
      PORT: 5555

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Start backend
        run: |
          node backend/index.js &
          npx wait-on http://127.0.0.1:5555/health

      - name: Start frontend (Vite)
        working-directory: frontend
        run: |
          npm run dev &
          npx wait-on http://localhost:5173

      - name: Run Playwright tests
        working-directory: frontend
        run: npx playwright test --reporter=html --trace on-first-retry

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          if-no-files-found: ignore

      - name: Upload Playwright traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: frontend/test-results
          if-no-files-found: ignore
